ALTER TABLE BANK_RECORD ADD CREATED DATE;
ALTER TABLE ACCOUNT ADD DATE_FORMAT VARCHAR2(15);
ALTER TABLE TRANSACTION ADD RELATIONSHIP VARCHAR2(10);
ALTER TABLE CATEGORY ADD ASSET_LIABILITY_ACTION NUMBER(19,0);
ALTER TABLE CATEGORY ADD ASSET_LIABILITY_ID NUMBER(19,0);

CREATE TABLE USER_TABLE(
  ID NUMBER(19,0), 
	VERSION NUMBER(19,0), 
  USER_NAME VARCHAR2(225),
  PASSWORD VARCHAR2(225),
  NAME VARCHAR2(225));
  ALTER TABLE USER_TABLE ADD PRIMARY KEY ("ID");
  CREATE UNIQUE INDEX USER_TABLE_NAME_UNIQUE ON USER_TABLE (USER_NAME); 
  ALTER TABLE USER_TABLE MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE USER_TABLE MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE USER_TABLE MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE USER_TABLE MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE USER_TABLE MODIFY ("NAME" NOT NULL ENABLE);
  